
owner: indietechteam # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Indie
    url: https://indie.work
  - name: Aux
    url: https://aux.app
  - name: Direct
    url: https://direct.app
  - name: benbowler.com
    url: https://benbowler.com
  - name: G0 Labs
    url: https://g0labs.com
  - name: RePatched
    url: https://repatched.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.indie.work
  # baseUrl: /your-repo-name
  logoUrl: https://indie.work/Indie-logo-white-on-black-square.svg
  name: Indie Status
  introTitle: "Tracking the status of Indie project sites."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: About Ben Bowler
      href: https://benbowler.com
    - title: Indie
      href: https://indie.work

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
